cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/Users/danrobertson/Docs/School/Networks/code/ns-allinone-3.19/ns-3.19/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/Users/danrobertson/Docs/School/Networks/code/ns-allinone-3.19/ns-3.19/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 6815216: cxx test.cpp -> test.cpp.1.o}\n[\'/usr/bin/g++\', \'-O0\', \'-ggdb\', \'-g3\', \'-Wall\', \'-Werror\', \'-arch\', \'x86_64\', \'-arch\', \'i386\', \'-fno-strict-aliasing\', \'-fno-common\', \'-dynamic\', \'-arch\', \'x86_64\', \'-arch\', \'i386\', \'-fno-common\', \'-fno-strict-aliasing\', \'-fwrapv\', \'-mno-fused-madd\', \'-fwrapv\', \'-DNS3_ASSERT_ENABLE\', \'-DNS3_LOG_ENABLE\', \'-DPYTHONDIR="/usr/local/lib/python2.7/site-packages"\', \'-DPYTHONARCHDIR="/usr/local/lib/python2.7/site-packages"\', \'-DENABLE_DTRACE\', \'-DMACOSX\', \'-DNDEBUG\', \'-DNDEBUG\', \'-DENABLE_DTRACE\', \'../test.cpp\', \'-c\', \'-o\', \'test.cpp.1.o\']\n'
